# Use postgres/example user/password credentials

services:

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: secret123
      DB_NAME: delivery_ya
      DB_SYNCHRONIZE: true
    depends_on:
      - db

  db:
    image: postgres:15.19
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: delivery_ya
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
